server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: booking-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/bookings/**

        - id: tracking-service-live
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/trains/*/live-status, /api/v1/trains/*/maps-config

        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/trains/**, /api/v1/stations/**

        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/payments/**

        - id: tracking-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/tracking/**

        - id: tracking-websocket
          uri: ws://localhost:8085
          predicates:
            - Path=/ws/**

        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/notifications/**
