apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: railconnect
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: railconnect
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: railconnect
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: railconnect
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: railconnect
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: railconnect
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: railconnect
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: booking-service
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: railconnect
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: inventory-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: railconnect
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: railconnect
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: tracking-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: railconnect
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: notification-service
