package com.railconnect.enums;
public enum BookingStatus {
    PENDING, CONFIRMED, WAITLISTED, CANCELLED, REFUNDED,
    TATKAL_CONFIRMED, PREMIUM_TATKAL_CONFIRMED, PARTIALLY_CONFIRMED, INITIATED, RAC
}
